//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _04_Entitiy_Framework_Linq_Projesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKULUPLER
    {
        public byte KULUPID { get; set; }
        public string KULUPAD { get; set; }
    }
}
